// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.6
// source: RobotNotConnectedAlert.proto

package event_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RobotNotConnectedAlert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"timestamp"
	Publishtime string `protobuf:"bytes,1,opt,name=publishtime,proto3" json:"timestamp"`
	// @inject_tag: json:"DataType"
	DataType string `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,3,opt,name=Email,proto3" json:"email"`
}

func (x *RobotNotConnectedAlert) Reset() {
	*x = RobotNotConnectedAlert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RobotNotConnectedAlert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotNotConnectedAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotNotConnectedAlert) ProtoMessage() {}

func (x *RobotNotConnectedAlert) ProtoReflect() protoreflect.Message {
	mi := &file_RobotNotConnectedAlert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotNotConnectedAlert.ProtoReflect.Descriptor instead.
func (*RobotNotConnectedAlert) Descriptor() ([]byte, []int) {
	return file_RobotNotConnectedAlert_proto_rawDescGZIP(), []int{0}
}

func (x *RobotNotConnectedAlert) GetPublishtime() string {
	if x != nil {
		return x.Publishtime
	}
	return ""
}

func (x *RobotNotConnectedAlert) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *RobotNotConnectedAlert) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_RobotNotConnectedAlert_proto protoreflect.FileDescriptor

var file_RobotNotConnectedAlert_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x0e, 0x62, 0x71, 0x5f, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x62, 0x71, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10, 0xea, 0x3f, 0x0d, 0x08,
	0x01, 0x12, 0x09, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x52, 0x0b, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x08, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xea, 0x3f, 0x02,
	0x08, 0x01, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x3a, 0x1b, 0xea, 0x3f, 0x18, 0x0a, 0x16, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x42,
	0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6c,
	0x61, 0x76, 0x61, 0x79, 0x73, 0x73, 0x69, 0x65, 0x72, 0x65, 0x2d, 0x73, 0x70, 0x6f, 0x6f, 0x6e,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_RobotNotConnectedAlert_proto_rawDescOnce sync.Once
	file_RobotNotConnectedAlert_proto_rawDescData = file_RobotNotConnectedAlert_proto_rawDesc
)

func file_RobotNotConnectedAlert_proto_rawDescGZIP() []byte {
	file_RobotNotConnectedAlert_proto_rawDescOnce.Do(func() {
		file_RobotNotConnectedAlert_proto_rawDescData = protoimpl.X.CompressGZIP(file_RobotNotConnectedAlert_proto_rawDescData)
	})
	return file_RobotNotConnectedAlert_proto_rawDescData
}

var file_RobotNotConnectedAlert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RobotNotConnectedAlert_proto_goTypes = []interface{}{
	(*RobotNotConnectedAlert)(nil), // 0: event_data.RobotNotConnectedAlert
}
var file_RobotNotConnectedAlert_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RobotNotConnectedAlert_proto_init() }
func file_RobotNotConnectedAlert_proto_init() {
	if File_RobotNotConnectedAlert_proto != nil {
		return
	}
	file_bq_table_proto_init()
	file_bq_field_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RobotNotConnectedAlert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RobotNotConnectedAlert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RobotNotConnectedAlert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RobotNotConnectedAlert_proto_goTypes,
		DependencyIndexes: file_RobotNotConnectedAlert_proto_depIdxs,
		MessageInfos:      file_RobotNotConnectedAlert_proto_msgTypes,
	}.Build()
	File_RobotNotConnectedAlert_proto = out.File
	file_RobotNotConnectedAlert_proto_rawDesc = nil
	file_RobotNotConnectedAlert_proto_goTypes = nil
	file_RobotNotConnectedAlert_proto_depIdxs = nil
}
